[package]
name = "venta_tauri"
version = "1.0.0"
description = "ALTO TRAGO - Sistema de gestion para vinoteca"
authors = ["Software Venta"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = { version = "0.4", default-features = true, features = ["clock"] }
